### ISSUE TITLE
dir.listFiles()方法获取不到jar包

### ISSUE THREAD

**Issue by youzipipi** [tianshanfz/java-plugin-demo#1]

**Comment by youzipipi** [comment]
经测试，PluginManager的initLoader方法中，dir.listFiles()获取到的File[] files为空

**Comment by tianshanfz** [comment]
> 经测试，PluginManager的initLoader方法中，dir.listFiles()获取到的File[] files为空

样例代码中将插件的"生成"和"引用"视为两个独立项目。
plugindemo：插件生成
plugindemocaller：插件引用
如果要直接运行“引用”项目，需要将java的工作目录调整在plugindemocaller（获移动plugindemo.jar到你的工作目录下）。

如果调整后还有问题，可以发出你的操作系统、java版本、完整目录结构、工作路径等信息

**Comment by youzipipi** [comment]
> 

好的明白您的意思的，感谢解答
